### ISSUE TITLE
Optimised Run ID Extraction Process

### ISSUE THREAD

**Issue by lasith-kg** [Codex-/return-dispatch#174]
It is possible to dynamically name a GitHub Workflow Run using the `run-name` attribute. In the workflow that is to be triggered by the `return-dispatch` action, it is possible to include the `dispatch_id` within the run name [[Reference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-run-name)]

```
name: example-workflow
run-name: Example Workflow [${{ inputs.distinct_id }}]

on:
  workflow_dispatch:
    inputs:
      distinct_id:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello World"
```

It is then possible to extract the `run_id` by doing a `String.contains(distinct_id)` search on the `name` attribute of the response returned by `/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs` [[Reference](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-required-workflow)]. The Run ID is available from the corresponding `id` attribute.

**Benefits**
-  Removes the need for a separate query to the `/repos/{owner}/{repo}/actions/runs/{run_id}/jobs` endpoint to try extract the `distinct_id` from the Jobs.
- I believe with these changes, it is possible to extract the Run ID while the workflow is in queue to be picked up by a GitHub Runner. This is from my assumption, that the name of the workflow is available before the initial Job is picked up by a GitHub Runner. This would reduce the time taken for this action to successfully fetch a Run ID

**Challenges**
- A hard change to the current process of retrieving the Run ID would break backwards compatibility with existing workflows that depend on this action assuming that the `distinct_id` is somewhere within the Jobs. Perhaps a backwards compatibility layer can be introduced to check the `distinct_id` from the Jobs if it can't be found in the Workflow Run name. 
  - It is computationally negligible  to do a `String.contains()` search on 10 strings, so I don't see an issue with this approach
