### ISSUE TITLE
distinct_id is not accepted by GitHub API

### ISSUE THREAD

**Issue by carlobeltrame** [Codex-/return-dispatch#292]
When using this action with settings like the following:
```yaml
      - name: Trigger something
        uses: Codex-/return-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ matrix.wagon.repo }}
          owner: ${{ matrix.wagon.owner }}
          ref: master
          workflow: tests.yml
          workflow_inputs: |
            {
              "core_ref": "${{ inputs.core_ref || github.ref || 'master' }}"
            }
```

I get an error saying the following:
```
❗  ::error::dispatchWorkflow: An unexpected error has occurred: Unexpected inputs provided: ["distinct_id"] - https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event
❗  ::error::Failed: Unexpected inputs provided: ["distinct_id"] - https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event
🚧  ::warning::Does the token have the correct permissions?
❗  ::error::Unexpected inputs provided: ["distinct_id"] - https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event
```

My token is a PAT with repo, actions read and actions write permissions.

To run this action, I am so far using [act](https://github.com/nektos/act) to run my workflow locally before pushing it to the repo, but regardless of where I run it, the documentation does not mention any parameter called `distinct_id`. When I remove this parameter, the action runs fine as far as I can tell.

Did this parameter get spontaneously removed in the GitHub API? Do you want me to open a PR to remove the distinct_id entirely? Do you have any idea what is going on?
