### ISSUE TITLE
Is there any way to pass a variable value as a workflow_input?

### ISSUE THREAD

**Issue by rashforth** [Codex-/return-dispatch#87]
The comments in your repo indicate that a workflow_input can only be a string. Do you have any suggestions on how to pass the value of a variable to the dispatched workflow?

**Comment by Codex-** [comment]
You should be able to do this using standard [github expressions](https://docs.github.com/en/actions/learn-github-actions/expressions)

You'd probably be doing this already for your token to include it from secrets, an example of this would be:
```yaml
steps:
  - name: Dispatch an action and get the run ID
    uses: codex-/return-dispatch@v1
    id: return-dispatch
    with:
      token: ${{ secrets.token }}
      ref: target_branch
      repo: repo
      owner: owner
      workflow: x.yml
      workflow_inputs: { "input_var": "${{ <expression> }}" }
```

Where `<expression>` can just be a reference to something you've populated in the [environment](https://docs.github.com/en/actions/learn-github-actions/environment-variables). There are quite a few ways to populate the env or add what you need, if you need some examples of this let me know :) 

On your recipient workflow you would have an input that maps to `input_var`:
```yaml
on:
  workflow_dispatch:
    inputs:
      distinct_id:
        required: true
      input_var:
        required: true
```
